### ISSUE TITLE
Comes up as "Undefined" in MM Dashboard

### ISSUE THREAD

**Issue by djastek** [dekinet/MMM-TranslinkBrisbane#2]
Widget hasn't loaded for the past week or so. Appears on the dashboard as "Undefined". Errors in the command line refer to "Cannot read properties for NULL (reading 'getElementsByTagName').

**Comment by dekinet** [comment]
Thanks for the heads-up. Looks like Translink has changed how their webpage is structured. A more thorough solution would be to used Translink's real-time feed (https://translink.com.au/about-translink/open-data), but I don't currently have the time to figure out how that works. I have updated the module to utilise the new webpage content - please pull the latest version from github.

**Comment by djastek** [comment]
Thanks @dekinet - I can confirm it's working again. Thanks very much for responding and fixing it so quickly. Much appreciated!
