### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by KristjanESPERANTO** [dekinet/MMM-TranslinkBrisbane#3]
Thanks for the module! Would be nice if you would add a screenshot :smiley:

**Comment by dekinet** [comment]
Not very visually exciting, but done.

**Comment by KristjanESPERANTO** [comment]
Thanks! One detail: Can you put the screenshot into the repository? Then it would be nicely displayed in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on :smiley:

**Comment by dekinet** [comment]
Is there anywhere in particular in the source tree it needs to be for your module to "find" it?

**Comment by dekinet** [comment]
Done.

**Comment by KristjanESPERANTO** [comment]
Nice. Now it's displayed with the screenshot :smiley:

Because I prefer black background and keywords are missing, I made a review of your code and opened a PR: #4.
